export const TOPBAR_MENU_ITEMS_ABOUT = `TOPBAR_MENU_ITEMS_ABOUT`
export const TOPBAR_MENU_ITEMS_EXPERIENCES = `TOPBAR_MENU_ITEMS_EXPERIENCES`
export const TOPBAR_MENU_ITEMS_TECHNOLOGIES = `TOPBAR_MENU_ITEMS_TECHNOLOGIES`
export const TOPBAR_MENU_ITEMS_CONTACT = `TOPBAR_MENU_ITEMS_CONTACT`

export const NAME = `NAME`
export const TITLE = `TITLE`

export const ABOUT_TITLE = `ABOUT_TITLE`
export const ABOUT_TEXT = `ABOUT_TEXT`
