export const NAME = `NAME`
export const TITLE = `TITLE`
export const SUBTITLE = `SUBTITLE`

export const SOFT_SKILLS_TITLE = `SOFT_SKILLS_TITLE`
export const HARD_SKILLS_TITLE = `HARD_SKILLS_TITLE`
export const TOOLS_TITLE = `TOOLS_TITLE`

export const ABOUT_TEXT = `ABOUT_TEXT`

export const CAREER_TITLE = `CAREER_TITLE`
export const CAREER_TEXT = `CAREER_TEXT`
export const WORK_EXPERIENCES_TITLE = `WORK_EXPERIENCES_TITLE`
export const WORK_EXPERIENCES = `WORK_EXPERIENCES`
